setup of backend and frontend
kalviumcommunity/Talking-Lands-training pull request #1
Opened 2023-06-20 09:27 UTC by akshithku

Frontend and Backend setup was done.

2023-06-20 09:37 UTC, kutty023 reviewed
Delete unwanted files

2023-06-21 07:20 UTC, PatelNeelMahesh requested changes
You have uploaded node_modules in backend, also do the below asked changes.

2023-06-21 07:20 UTC, PatelNeelMahesh commented on Backend/package.json
> +    "i": "^0.3.7"
You have added wrong dependency here remove it.

2023-06-21 07:20 UTC, PatelNeelMahesh commented on frontend/README.md
> +# Getting Started with Create React App
Remove default Readme generated by create-react-app and add your project component details, figma file etc.

2023-06-21 07:20 UTC, PatelNeelMahesh commented on frontend/package.json
> +  "name": "frontend",
Add your project nane here.

2023-07-04 07:52 UTC, PatelNeelMahesh requested changes
node_module folder is available in PR, delete from here.

2023-07-05 03:50 UTC, PatelNeelMahesh approved these changes
You can merge pull request, after deleting the folder from the PR.

2023-07-07 11:16 UTC, merged